[package]
name = "blackenedgold/idris-posix-sandbox"
version = "0.1.0"
authors = []

[dependencies]

[[targets.bin]]
path = "src"
name = "idris-posix-sandbox"
main = "Main"
idris_opts = ["-p", "posix"]

